=== adam-poteralowicz/pwr-xmllint/plik.xsd
<?xml version="1.0" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <xsd:element name="BOOK">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element name="BOOKTITLE" type="xsd:string"/>
            <xsd:element name="AUTHOR" type="xsd:string"/>
            <xsd:element name="INTRO" type="xsd:string"/>
            <xsd:element name="CHAPTER" type="xsd:string">
            	<xsd:complexType>
            		<xsd:simpleContent>
            			<xsd:element name="CHAPTERTITLE" type="xsd:string"/>
            			<xsd:element name="PAGE" type="xsd:int"/>
            			<xsd:element name="SECTION" type="xsd:string">
            				<xsd:complexType>
            					<xsd:sequence>
            						<xsd:element name="SECTIONTITLE" type="xsd:string"/>
            						<xsd:element name="PARAGRAPH" type="xsd:string"/>
            					</xsd:sequence>
            				</xsd:complexType>
            			</xsd:element>
            			<xsd:element name="SECTION" type="xsd:string">
            				<xsd:complexType>
            					<xsd:sequence>
            						<xsd:element name="SECTIONTITLE" type="xsd:string"/>
            						<xsd:element name="PARAGRAPH" type="xsd:string"/>
            					</xsd:sequence>
            				</xsd:complexType>
            			</xsd:element>
            			<xsd:element name="SECTION" type="xsd:string">
            				<xsd:complexType>
            					<xsd:sequence>
            						<xsd:element name="SECTIONTITLE" type="xsd:string"/>
            						<xsd:element name="PARAGRAPH" type="xsd:string"/>
            					</xsd:sequence>
            				</xsd:complexType>
            			</xsd:element>
            		</xsd:sequence>
            	</xsd:complexType>
            </xsd:element>
            <xsd:element name="CHAPTER" type="xsd:string">
            	<xsd:complexType>
            		<xsd:sequence>
            			<xsd:element name="CHAPTERTITLE" type="xsd:string"/>
            			<xsd:element name="PAGE" type="xsd:int"/>
            			<xsd:element name="SECTION" type="xsd:string">
            				<xsd:complexType>
            					<xsd:sequence>
            						<xsd:element name="SECTIONTITLE" type="xsd:string"/>
            						<xsd:element name="PARAGRAPH" type="xsd:string"/>
            					</xsd:sequence>
            				</xsd:complexType>
            			</xsd:element>
            			<xsd:element name="SECTION" type="xsd:string">
            				<xsd:complexType>
            					<xsd:sequence>
            						<xsd:element name="SECTIONTITLE" type="xsd:string"/>
            						<xsd:element name="PARAGRAPH" type="xsd:string"/>
            					</xsd:sequence>
            				</xsd:complexType>
            			</xsd:element>
            			<xsd:element name="SECTION" type="xsd:string">
            				<xsd:complexType>
            					<xsd:sequence>
            						<xsd:element name="SECTIONTITLE" type="xsd:string"/>
            						<xsd:element name="PARAGRAPH" type="xsd:string"/>
            					</xsd:sequence>
            				</xsd:complexType>
            			</xsd:element>
            		</xsd:sequence>
            	</xsd:complexType>
            </xsd:element>
            <xsd:element name="CHAPTER" type="xsd:string">
            	<xsd:complexType>
            		<xsd:sequence>
            			<xsd:element name="CHAPTERTITLE" type="xsd:string"/>
            			<xsd:element name="PAGE" type="xsd:int"/>
            			<xsd:element name="SECTION" type="xsd:string">
            				<xsd:complexType>
            					<xsd:sequence>
            						<xsd:element name="SECTIONTITLE" type="xsd:string"/>
            						<xsd:element name="PARAGRAPH" type="xsd:string"/>
            					</xsd:sequence>
            				</xsd:complexType>
            			</xsd:element>
            			<xsd:element name="SECTION" type="xsd:string">
            				<xsd:complexType>
            					<xsd:sequence>
            						<xsd:element name="SECTIONTITLE" type="xsd:string"/>
            						<xsd:element name="PARAGRAPH" type="xsd:string"/>
            					</xsd:sequence>
            				</xsd:complexType>
            			</xsd:element>
            			<xsd:element name="SECTION" type="xsd:string">
            				<xsd:complexType>
            					<xsd:sequence>
            						<xsd:element name="SECTIONTITLE" type="xsd:string"/>
            						<xsd:element name="PARAGRAPH" type="xsd:string"/>
            					</xsd:sequence>
            				</xsd:complexType>
            			</xsd:element>
            		</xsd:sequence>
            	</xsd:complexType>
            </xsd:element>
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>
</xsd:schema>

=== adam-poteralowicz/pwr-xmllint/plik2.xml
<?xml version="1.0"?> 


<BOOK>
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="plik.xsd">
   <BOOKTITLE>Grapes of Wrath</BOOKTITLE>
   <AUTHOR>Steinbeck, John</AUTHOR>
   <INTRO>20th century literature</INTRO>
   <CHAPTER>
      <CHAPTERTITLE>Chapter 1</CHAPTERTITLE>
      <PAGE>1</PAGE>
      <SECTION>
         <SECTIONTITLE>Section 1</SECTIONTITLE>
         <PARAGRAPH>First</PARAGRAPH>
      </SECTION>
      <SECTION>
         <SECTIONTITLE>Section 2</SECTIONTITLE>
         <PARAGRAPH>First</PARAGRAPH>
      </SECTION>
      <SECTION>
         <SECTIONTITLE>Section 3</SECTIONTITLE>
         <PARAGRAPH>First</PARAGRAPH>
      </SECTION>
   </CHAPTER>
   <CHAPTER>
      <CHAPTERTITLE>Chapter 2</CHAPTERTITLE>
      <PAGE>1</PAGE>
      <SECTION>
         <SECTIONTITLE>Section 1</SECTIONTITLE>
         <PARAGRAPH>First</PARAGRAPH>
      </SECTION>
      <SECTION>
         <SECTIONTITLE>Section 2</SECTIONTITLE>
         <PARAGRAPH>First</PARAGRAPH>
      </SECTION>
      <SECTION>
         <SECTIONTITLE>Section 3</SECTIONTITLE>
         <PARAGRAPH>First</PARAGRAPH>
      </SECTION>
   </CHAPTER>
   <CHAPTER>
      <CHAPTERTITLE>Chapter 3</CHAPTERTITLE>
      <PAGE>1</PAGE>
      <SECTION>
         <SECTIONTITLE>Section 1</SECTIONTITLE>
         <PARAGRAPH>First</PARAGRAPH>
      </SECTION>
      <SECTION>
         <SECTIONTITLE>Section 2</SECTIONTITLE>
         <PARAGRAPH>First</PARAGRAPH>
      </SECTION>
      <SECTION>
         <SECTIONTITLE>Section 3</SECTIONTITLE>
         <PARAGRAPH>First</PARAGRAPH>
      </SECTION>
   </CHAPTER>
</BOOK>
